nome=str(input('Digite seu nome completo: ')).strip()
maiuscula=nome.upper()
print('O nome em maiúsculo é: {}'.format(maiuscula))
minuscula=nome.lower()
print('O nome em minúsculo é: {}'.format(minuscula))
print('A quantidade ao todo de letras é: {}'.format(len(nome)-nome.count(' ')))
#print('O primeiro nome tem {} caracteres'.format(nome.find(' ')))
separa=nome.split()
print('Seu primeiro nome é {} e tem {} letras'.format(separa[0], len(separa[0])))