mostre=(input('Tecle algo:'))
print('O tipo primitivo deste valor é:', type(mostre))
print('É númerico?', mostre.isnumeric())
print('É alfabético?', mostre.isalpha())
print('É alfanumerico?', mostre.isalnum())
print('Só tem maíusculas?', mostre.isupper())
print('É um espaço?', mostre.isspace())
print('É impresso?', mostre.isprintable())
print('Está capitalizada?', mostre.istitle())